### ISSUE TITLE
Getting Rate-Limitited while having 1-minute breaks in-between

### ISSUE THREAD

**Issue by CezaPasc** [deedy5/duckduckgo_search#213]
## Describe the bug

I am getting rate-limited receiving a 202 Status Code even though I am waiting at least 1 minute between the requests.  It usually happens after 6-7 requests
I'm not sure if it matters, but I'm still able to visit `https://duckduckgo.com/`in the browser after being rate-limited.

**Steps to reproduce the problem:**
The problem can be reproduced executing this:

```python
from duckduckgo_search import DDGS
import time

class DuckDuckGo:

    def __init__(self, limit=5) -> None:
        self.limit = limit
        self.query = ""
        self.duck = DDGS()
        self.new_search = False
        self.last_request = 0
        self.cooldown = 60

    def perform_search(self):
        assert self.query != "", "Please set a search query first using `set_search(query)`"
        now = time.time()
        difference = now - self.last_request
        if difference < self.cooldown:
            to_wait = self.cooldown - difference
            print("Waiting %s before next request" % to_wait)
            time.sleep(to_wait)

        # Send the request
        results = self.duck.text(self.query, max_results=self.limit)
        self.new_search = False
        self.last_request = time.time()

        for result in results:
            result["link"] = result.pop("href") 

        return results

    def set_search(self, query):
        self.query = f'site:finance.yahoo.com/news/ "{query}"'
        self.new_search = True



if __name__ == "__main__":
    duck = DuckDuckGo()

    while True:
        duck.set_search("some")
        results = duck.perform_search()

        duck.set_search("search")
        results = duck.perform_search()

        duck.set_search("terms")
        results = duck.perform_search()

```

Exception:
`
duckduckgo_search.exceptions.RatelimitException: https://duckduckgo.com/ 202 Ratelimit
`

**Specify this information**

 - OS: Mac OS 14.2
 - environment: Python 3.10
 - duckduckgo_search version: 5.3.0

**Comment by deedy5** [comment]
Try the version with httpx for now:
`pip install -U duckduckgo_search==5.3.0b4`

**Comment by av1d** [comment]
Was having same issue, the httpx version fixed it. Thank you.

**Comment by CezaPasc** [comment]
I am now using this version and I am still facing the same issue.
`duckduckgo_search  5.3.0b4`

Do I also have to change something in the code, like specifying a different backend?

**Comment by DavidEstape** [comment]
Trying the suggested version (5.3.0b4) also solved the problem for me.
`pip install -U duckduckgo_search==5.3.0b4`

In case you are using Windows, you also have to change the default EventLoopPolicy of asyncio library BEFORE importing the other libraries.
```
import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

I don't know if I will be rate-limited again with the httpx version after a while...

**Comment by deedy5** [comment]
@CezaPasc 
>I am now using this version and I am still facing the same issue.
duckduckgo_search  5.3.0b4
Do I also have to change something in the code, like specifying a different backend?

Changing the `backend` parameter will not provide any benefits.

**Comment by DavidEstape** [comment]
> @DavidEstape
> 
> > In case you are using Windows, you also have to change the default EventLoopPolicy of asyncio library BEFORE importing the other libraries.
> 
> This is applied automatically: https://github.com/deedy5/duckduckgo_search/blob/fce7fab463934f9e4d844ca5ca40a185a656a468/duckduckgo_search/__init__.py#L18C1-L19C76

Yes. You are correct. I tried without and no warning now, so no need to change the EventLoopPolicy.
Thank you for your effort.

**Comment by deedy5** [comment]
@CezaPasc 

There's a new version (v5.3.1) out, give it a try.
`pip install -U duckduckgo_search`

**Comment by syshin01166** [comment]
solved with `pip install -U duckduckgo_search` to v5.3.1

**Comment by CezaPasc** [comment]
Could it be that the problem is somehow on my fault?
I tested it now again twice: in the same environment and then on an other server (using Linux instead of Mac OS) with a fresh Python environment only having duckduckgo_search installed.
`duckduckgo_search 5.3.1`

**Comment by jzxcd** [comment]
Still running into the same after update to v5.3.1. Was running 1 search per 3-5 sec for total ~50 searches. The error message is bit confusing since I can see the search output in the provide url. Do we just wait it out for soft block period or there is a fix?

```
RatelimitException: https://links.duckduckgo.com/d.js?q=sklearn+repo+site%3Agithub.com&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-292300349075791261695672170567302953005&ex=-1 202 Ratelimit
```

**Comment by moraneden** [comment]
duckduckgo_search==5.3.0b4 works for me while 5.3.1 still fails

**Comment by AlexUmnov** [comment]
I'll leave my two cents here. 
I was using this lib with langchain inside Collaboratory. 
Restarting the runtime fixed it, while every other solution didn't.

**Comment by vk-maurya** [comment]
I am using windows system its working 
after  adding code below code before
```
import asyncio

asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

from duckduckgo_search import DDGS

results = DDGS().text("who twitter ceo", max_results=5)
print(results)
```
Thanks @DavidEstape

**Comment by deedy5** [comment]
What is the current situation?
Does anyone have v5.3.1 or 5.3.1b1 working?

**Comment by aliciannz** [comment]
Neither 5.3.1 nor 5.3.1b1 is working for me. In my case, it freezes forever instead of raising an exception. However, 5.3.0b4 seems to be working.

**Comment by deedy5** [comment]
Update to v6.0.0

**Comment by vivekshinde27** [comment]
Using version 6.1.9 still facing this issue > RatelimitException: https://duckduckgo.com/ 202 Ratelimit

**Comment by yshishenya** [comment]
> Using version 6.1.9 still facing this issue > RatelimitException: https://duckduckgo.com/ 202 Ratelimit
Having the same issue

**Comment by deedy5** [comment]
update to v6.1.10

**Comment by LanceLake** [comment]
Updated to 6.2.10 and running this..

import duckduckgo_search

print(f"Running duckduckgo_search version {duckduckgo_search.__version__}\n")
query = "test test 123"

with duckduckgo_search.DDGS() as ddgs:
    instant_answers = ddgs.answers(query)
    if instant_answers:
        print(instant_answers)
    for result in ddgs.text(query, region='wt-wt', safesearch='moderate', timelimit=None, max_results=10):
        print(result["title"])
        print(result["href"])
        print(result["body"])
        print()

shows the error.

![image](https://github.com/user-attachments/assets/46c52f11-5c82-4bce-b95a-49c6880ea093)

**Comment by deedy5** [comment]
1) use the latest version,
2) don't use `backend`="html" or "lite" at all,
3) if you send too many requests, you will be blocked for a while,
4) If your ISP blocks access to duckduckgo, [use a proxy](https://github.com/deedy5/duckduckgo_search?tab=readme-ov-file#proxy).

**Comment by LanceLake** [comment]
1. I am (as I stated).
2. The code I posted doesn't use either of those. 

```
import duckduckgo_search

print(f"Running duckduckgo_search version {duckduckgo_search.__version__}\n")
query = "test test 123"

with duckduckgo_search.DDGS() as ddgs:
    instant_answers = ddgs.answers(query)
    if instant_answers:
        print(instant_answers)
    for result in ddgs.text(query, region='wt-wt', safesearch='moderate', timelimit=None, max_results=10):
        print(result["title"])
        print(result["href"])
        print(result["body"])
        print()
```
3. This is erroring on my first quote.
4. My ISP doesn't block access to it.

I am doing all those things. Still broken.

**Comment by deedy5** [comment]
I can't reproduce your problem. It's working properly.

**Comment by LanceLake** [comment]
It's working properally for you. It isn't for me. But since you can't reproduce it, then I'll wait until other people point this out and you have more data to go on. Thanks anyway.

**Comment by banteng56** [comment]
have updated the latest DDGS and have done IP rotation. Why am I still getting the 202 rate limit?

**Comment by CezaPasc** [comment]
I guess if this problem occurs also depends on your geolocation. While being in the Philippines it didn’t occur once for me.

**Comment by banteng56** [comment]
I live in Indonesia where DDGS is blocked, and I'm using the default DNS 8.8.8.8 to access it, but I'm also using rotating proxies for my program. Could this DNS cause any issues?

**Comment by deedy5** [comment]
Change `proxy=socks5://...` to `proxy=socks5h://`.
When you use `socks5h://`, DNS resolution is performed by the SOCKS5 proxy itself.

**Comment by banteng56** [comment]
cool mate, ive tried it with vpn an then do proxy like u write in github. thanks

**Comment by banteng56** [comment]
Sorry, I would like to ask again, can the ddgs library use SSL certificates? I encountered an error: 'ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002).
